import Image from 'next/image'
import Layout from '../components/Layout'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={` h-full  bg-orange-700`}>
        <div>

        </div>
      </section>

    </>

  )
}
